# permissions for end users to view transportserverclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: transportserverclaim-viewer-role
rules:
- apiGroups:
  - porter.devops.gov.bc.ca
  resources:
  - transportserverclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - porter.devops.gov.bc.ca
  resources:
  - transportserverclaims/status
  verbs:
  - get
